DoubleLinkedList
VctPerez/TestsPracticas pull request #5
Opened 2024-03-19 13:06 UTC by JoseBueno30

2024-03-19 13:22 UTC, DavidBuenoCarmona approved these changes

2024-03-19 13:23 UTC, DavidBuenoCarmona approved these changes

2024-03-19 13:23 UTC, DavidBuenoCarmona approved these changes

2024-03-19 13:24 UTC, DavidBuenoCarmona reviewed
FALLO

2024-03-20 08:44 UTC, VctPerez requested changes

2024-03-20 08:44 UTC, VctPerez commented on DobleLinkedList_P2/src/test/java/org/mps/deque/DoubleLinkedListTest.java
> +    class DeleteFirst {
Cambiaría en los nombres de los metodos first, por deleteFirst

2024-03-20 08:44 UTC, VctPerez commented on DobleLinkedList_P2/src/test/java/org/mps/deque/DoubleLinkedListTest.java
> +    class DeleteLast {
Nombres mal puestos. First por deleteLast.

2024-03-20 08:44 UTC, VctPerez commented on DobleLinkedList_P2/src/test/java/org/mps/deque/DoubleLinkedListTest.java
> +    DoubleLinkedList<Object> list;
Yo le indicaría un tipo específico a los elementos de la lista.

2024-03-20 08:44 UTC, VctPerez commented on DobleLinkedList_P2/src/test/java/org/mps/deque/DoubleLinkedListTest.java
> +    class Last {
Cambiar first por last en los nombres de los metodos

2024-03-20 08:44 UTC, VctPerez commented on DobleLinkedList_P2/src/main/java/org/mps/deque/DoubleLinkedList.java
>  public class DoubleLinkedList<T> implements DoubleLinkedQueue<T> {
La clase de la lista no debería ocuparse de establecer el next y el previous de los nodos.

2024-04-03 08:06 UTC, DavidBuenoCarmona commented on DobleLinkedList_P2/src/main/java/org/mps/deque/DoubleLinkedList.java
> +            temporalNode.setPrevious(newNode);
hecho

2024-04-03 08:10 UTC, VctPerez approved these changes

2024-04-03 08:11 UTC, merged